
sudo: required

services:
  - docker

install:
  - curl https://get.docker.com/ | /bin/bash
  - docker -v
  - wget https://storage.googleapis.com/involucro-1149.appspot.com/involucro
  - chmod u+x involucro

script:
  - ./involucro -v main:generate_linuxbrew_builder > /dev/null
  - if [[ $TRAVIS_SECURE_ENV_VARS == "true" ]]; then docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io ; fi
  - (if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then ./involucro -v main:prepare deploy ; else ./involucro -v main:prepare test ; fi) > /dev/null

notifications:
  webhooks:
    - https://webhooks.gitter.im/e/54581d2e70d821f7839b
